### ISSUE TITLE
stacklet list doesn't show minio deployed via rendered manifests

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/stackable-cockpit#363]
### Affected version

pre 25.3.0

### Current and expected behavior

The service is looked up via labels:

https://github.com/stackabletech/stackable-cockpit/blob/c8f92b6b071e85f6b3998c20251c987f61c58aca/rust/stackable-cockpit/src/platform/stacklet/minio.rs#L16

But the labels are different when minio is deployed via rendered manifests (currently needed to enable TLS with secret-operator certs):

Labels for `minio-console` when deployed via Helm:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: default
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-5.3.0
    heritage: Helm
    release: minio
```

Labels for `minio-console` when deployed via manifests (pre-rendered via `helm template`):

```yml
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: default
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    release: minio
    stackable.tech/managed-by: stackablectl
    stackable.tech/stack: trino-superset-s3
    stackable.tech/vendor: Stackable
```

### Possible solution

Options:

1. Use different labels to lookup
2. Do two lookups (add a lookup to match on the new labels above).

### Additional context

Without this fix, the demos become confusing as they expect minio to be listed.

### Would you like to work on fixing this bug?

None
